/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package telas;

import despachantefacil.models.Veiculo;
import despachantefacil.models.dao.VeiculoDAO;
import despachantefacil.models.enums.CarroceriaENUM;
import despachantefacil.models.enums.CategoriaENUM;

/**
 *
 * @author vinic
 */
public class EditaVeiculoDialog extends javax.swing.JFrame {
    private Veiculo veiculo;

    /** Creates new form EditaVeiculoDialog */
    public EditaVeiculoDialog(int idVeiculo) {
        super("Editar Veículo");
        initComponents();
        preencherJComboBox1();
        preencherJComboBox2(); //inicializando o método para inserir os ENUMs nos Combo Box
        
        //conexão com o banco através do VeiculoDAO para buscar as informações do veículo através do idVeiculo
        VeiculoDAO veiculoDAO = new VeiculoDAO();
        this.veiculo = veiculoDAO.getVeiculoById(idVeiculo);
        
        if (this.veiculo == null) {
        System.out.println("Erro: Veículo com id " + idVeiculo + " não foi encontrado no banco de dados.");
        return;
    }
        
        //preenchendo as informações da tela com os dados do banco de dados
        this.txtPlaca.setText(veiculo.getPlaca());
        this.txtRenavam.setText(veiculo.getRenavam());
        this.txtChassi.setText(veiculo.getChassi());
        this.txtMarcaModelo.setText(veiculo.getMarcaModelo());
        this.txtAnoFab.setText(String.valueOf(veiculo.getAnoFab()));
        this.txtAnoMod.setText(String.valueOf(veiculo.getAnoMod()));
        this.txtObservacoes.setText(veiculo.getObservacoes());
        
        if(veiculo.getCarroceriaENUM() != null) {
            this.jComboBox2.setSelectedItem(veiculo.getCarroceriaENUM().toString());
        }else{
            System.out.println("Erro: Veículo com id " + idVeiculo + " não tem uma CarroceriaENUM definida.");
        }
        
        if(veiculo.getCategoriaENUM()!= null) {
            this.jComboBox1.setSelectedItem(veiculo.getCategoriaENUM().toString());
        }else{
            System.out.println("Erro: Veículo com id " + idVeiculo + " não tem uma CategoriaENUM definida.");
        }
    
    }
    
    //configurando os combo box
    private void preencherJComboBox1(){
        jComboBox1.removeAllItems();
        CategoriaENUM[] categorias = CategoriaENUM.values();
        for (CategoriaENUM categoria : categorias){
            jComboBox1.addItem(categoria.name());
        }
    }
    
    private void preencherJComboBox2(){ 
        jComboBox2.removeAllItems();
        CarroceriaENUM[] carrocerias = CarroceriaENUM.values();
        for (CarroceriaENUM carroceria : carrocerias){
            jComboBox2.addItem(carroceria.name());
        }
    }
    
    public void preencherCampos(Veiculo veiculo) {
        this.veiculo = veiculo; //salvando o veículo para uso posterior
        
        txtPlaca.setText(veiculo.getPlaca());
        txtRenavam.setText(veiculo.getRenavam());
        txtChassi.setText(veiculo.getChassi());
        txtMarcaModelo.setText(veiculo.getMarcaModelo());
        txtAnoFab.setText(String.valueOf(veiculo.getAnoFab()));
        txtAnoMod.setText(String.valueOf(veiculo.getAnoMod()));
        txtObservacoes.setText(veiculo.getObservacoes());
        jComboBox1.setSelectedItem(veiculo.getCategoriaENUM().name());
        jComboBox2.setSelectedItem(veiculo.getCarroceriaENUM().name());
  
    }
    
    public void atualizarVeiculo(){
        //atualizando o veículo com os dados dos campos
        veiculo.setPlaca(txtPlaca.getText());
        veiculo.setRenavam(txtRenavam.getText());
        veiculo.setChassi(txtChassi.getText());
        veiculo.setMarcaModelo(txtMarcaModelo.getText());
        veiculo.setAnoFab(Integer.parseInt(txtAnoFab.getText()));
        veiculo.setAnoMod(Integer.parseInt(txtAnoMod.getText()));
        veiculo.setObservacoes(txtObservacoes.getText());
        veiculo.setCategoriaENUM(CategoriaENUM.valueOf((String) jComboBox1.getSelectedItem()));
        veiculo.setCarroceriaENUM(CarroceriaENUM.valueOf((String) jComboBox2.getSelectedItem()));
        
        //salvando as alterações do veículo no banco de dados
        VeiculoDAO veiculoDAO = new VeiculoDAO();
        veiculoDAO.updateVeiculo(veiculo);
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtRenavam = new javax.swing.JTextField();
        txtChassi = new javax.swing.JTextField();
        txtMarcaModelo = new javax.swing.JTextField();
        txtAnoFab = new javax.swing.JTextField();
        txtAnoMod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Veículos");

        jLabel2.setText("Placa");

        jLabel3.setText("Renavam");

        jLabel4.setText("Chassi");

        jLabel5.setText("Marca/Modelo");

        jLabel6.setText("Ano Fab.");

        jLabel7.setText("Ano Mod.");

        jLabel8.setText("Tipo Carroceria");

        jLabel9.setText("Categoria");

        jLabel10.setText("Observações");

        txtAnoFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoFabActionPerformed(evt);
            }
        });

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtPlaca)
                            .addComponent(txtRenavam)
                            .addComponent(txtChassi)
                            .addComponent(txtMarcaModelo)
                            .addComponent(txtAnoFab)
                            .addComponent(txtAnoMod)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMarcaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAnoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnoFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoFabActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        atualizarVeiculo();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ListaVeiculos telaListaVeiculos = new ListaVeiculos();
        telaListaVeiculos.setVisible(true);
        this.dispose();  // Este comando vai fechar a tela atual
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAnoFab;
    private javax.swing.JTextField txtAnoMod;
    private javax.swing.JTextField txtChassi;
    private javax.swing.JTextField txtMarcaModelo;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRenavam;
    // End of variables declaration//GEN-END:variables

}
